# Generated by Django 5.2.4 on 2025-08-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_skill_customuser_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='freelancers', to='Account.skill'),
        ),
    ]
