# Generated by Django 5.2.4 on 2025-08-04 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_customuser_skills'),
        ('jobassignment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='Account.skill'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(limit_choices_to={'is_freelancer': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobassignment.job')),
            ],
            options={
                'unique_together': {('job', 'freelancer')},
            },
        ),
    ]
