# Generated by Django 5.2.4 on 2025-08-06 05:10

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobassignment', '0002_job_skills_jobapplication'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='milestone',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='jobassignme_title_057034_gin'),
        ),
    ]
