# Generated by Django 5.2.4 on 2025-08-06 05:13

from django.db import migrations

from django.contrib.postgres.operations import TrigramExtension , BtreeGinExtension
class Migration(migrations.Migration):

    dependencies = [
        ('jobassignment', '0003_milestone_jobassignme_title_057034_gin'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='milestone',
            name='jobassignme_title_057034_gin',
        ),
        BtreeGinExtension(),
    ]
  
